#!/bin/bash
echo "--- INICIANDO ATUALIZAÇÃO DO GENTOO ---"

echo "Sincronizando o Portage"
emerge --sync

echo "Atualizando os pacotes"
emerge --update --deep --changed-use --getbinpkg @world && {

    echo "Limpando dependências antigas"
    emerge --depclean

    echo "Verificando atualizações de arquivos de configuração"
    dispatch-conf

    echo "--- ATUALIZAÇÃO CONCLUÍDA COM SUCESSO! ---"
} || {
    echo "--- ERRO: A atualização falhou. Verifique acima ---"
    exit 1
}
