#!/bin/bash
temp=""
echo "--- INICIANDO ATUALIZAÇÃO DO GENTOO ---"

echo "Sincronizando o Portage"
emerge --sync

echo "Atualizando os pacotes"
emerge --update --deep --changed-use --getbinpkg @world && {
    read -p "Limpar dependências antigas? (S/n)" $temp
    if [[ $temp == "\n" ]] || [[ $temp == "s" ]] || [[ $temp == "S" ]]; then
        emerge --depclean
    fi

    echo "Verificando atualizações de arquivos de configuração"
    dispatch-conf

    echo "--- ATUALIZAÇÃO CONCLUÍDA COM SUCESSO! ---"
} || {
    echo "--- ERRO: A atualização falhou. Verifique acima ---"
    exit 1
}
